// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: internal/api/peer/v1/peer.proto

package peerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeerDiscoveryService_SyncDirectory_FullMethodName = "/weir.peer.v1.PeerDiscoveryService/SyncDirectory"
)

// PeerDiscoveryServiceClient is the client API for PeerDiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PeerDiscoveryService is internal node-to-node control traffic. It contains no
// public business DTOs and never carries a business request or response stream.
type PeerDiscoveryServiceClient interface {
	SyncDirectory(ctx context.Context, in *SyncDirectoryRequest, opts ...grpc.CallOption) (*SyncDirectoryResponse, error)
}

type peerDiscoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerDiscoveryServiceClient(cc grpc.ClientConnInterface) PeerDiscoveryServiceClient {
	client := &peerDiscoveryServiceClient{cc}
	return client
}

func (c *peerDiscoveryServiceClient) SyncDirectory(ctx context.Context, in *SyncDirectoryRequest, opts ...grpc.CallOption) (*SyncDirectoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncDirectoryResponse)
	err := c.cc.Invoke(ctx, PeerDiscoveryService_SyncDirectory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerDiscoveryServiceServer is the server API for PeerDiscoveryService service.
// All implementations must embed UnimplementedPeerDiscoveryServiceServer
// for forward compatibility.
//
// PeerDiscoveryService is internal node-to-node control traffic. It contains no
// public business DTOs and never carries a business request or response stream.
type PeerDiscoveryServiceServer interface {
	SyncDirectory(context.Context, *SyncDirectoryRequest) (*SyncDirectoryResponse, error)
	mustEmbedUnimplementedPeerDiscoveryServiceServer()
}

// UnimplementedPeerDiscoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerDiscoveryServiceServer struct{}

func (UnimplementedPeerDiscoveryServiceServer) SyncDirectory(context.Context, *SyncDirectoryRequest) (*SyncDirectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncDirectory not implemented")
}
func (UnimplementedPeerDiscoveryServiceServer) mustEmbedUnimplementedPeerDiscoveryServiceServer() {}
func (UnimplementedPeerDiscoveryServiceServer) testEmbeddedByValue()                              {}

// UnsafePeerDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerDiscoveryServiceServer will
// result in compilation errors.
type UnsafePeerDiscoveryServiceServer interface {
	mustEmbedUnimplementedPeerDiscoveryServiceServer()
}

func RegisterPeerDiscoveryServiceServer(s grpc.ServiceRegistrar, srv PeerDiscoveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedPeerDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerDiscoveryService_ServiceDesc, srv)
}

func _PeerDiscoveryService_SyncDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerDiscoveryServiceServer).SyncDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerDiscoveryService_SyncDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerDiscoveryServiceServer).SyncDirectory(ctx, req.(*SyncDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerDiscoveryService_ServiceDesc is the grpc.ServiceDesc for PeerDiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerDiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weir.peer.v1.PeerDiscoveryService",
	HandlerType: (*PeerDiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncDirectory",
			Handler:    _PeerDiscoveryService_SyncDirectory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/peer/v1/peer.proto",
}
