// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/api/peer/v1/peer.proto

package peerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncDirectoryRequest offers announcements learned locally or from other peers.
type SyncDirectoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Announcements must pass complete snapshot validation before any are merged.
	Announcements []*NodeAnnouncement `protobuf:"bytes,1,rep,name=announcements,proto3" json:"announcements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDirectoryRequest) Reset() {
	*x = SyncDirectoryRequest{}
	mi := &file_internal_api_peer_v1_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDirectoryRequest) ProtoMessage() {}

func (x *SyncDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_peer_v1_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDirectoryRequest.ProtoReflect.Descriptor instead.
func (*SyncDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_peer_v1_peer_proto_rawDescGZIP(), []int{0}
}

func (x *SyncDirectoryRequest) GetAnnouncements() []*NodeAnnouncement {
	if x != nil {
		return x.Announcements
	}
	return nil
}

// SyncDirectoryResponse provides the receiver's current discovery snapshot.
type SyncDirectoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relayed announcements report their remaining lease, never a renewed lease.
	Announcements []*NodeAnnouncement `protobuf:"bytes,1,rep,name=announcements,proto3" json:"announcements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDirectoryResponse) Reset() {
	*x = SyncDirectoryResponse{}
	mi := &file_internal_api_peer_v1_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDirectoryResponse) ProtoMessage() {}

func (x *SyncDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_peer_v1_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDirectoryResponse.ProtoReflect.Descriptor instead.
func (*SyncDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_peer_v1_peer_proto_rawDescGZIP(), []int{1}
}

func (x *SyncDirectoryResponse) GetAnnouncements() []*NodeAnnouncement {
	if x != nil {
		return x.Announcements
	}
	return nil
}

// NodeAnnouncement describes one process incarnation. Only its originating node
// advances the revision or renews its lease. A relay reduces the remaining lease.
type NodeAnnouncement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Random identity generated for this process lifetime; a restart gets a new ID.
	IncarnationId string `protobuf:"bytes,1,opt,name=incarnation_id,json=incarnationId,proto3" json:"incarnation_id,omitempty"`
	// Monotonic origin heartbeat sequence. Replaying a revision cannot extend its lease.
	Revision uint64 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	// Direct host:port endpoint for this node's PeerDiscoveryService listener.
	PeerEndpoint string `protobuf:"bytes,3,opt,name=peer_endpoint,json=peerEndpoint,proto3" json:"peer_endpoint,omitempty"`
	// Replicas in this group serve equivalent Store ownership. Different groups
	// advertising the same Store create an ownership conflict.
	ReplicaGroup string `protobuf:"bytes,4,opt,name=replica_group,json=replicaGroup,proto3" json:"replica_group,omitempty"`
	// Complete set of logical Stores served locally by this process.
	StoreNames []string `protobuf:"bytes,5,rep,name=store_names,json=storeNames,proto3" json:"store_names,omitempty"`
	// Reachable IP or DNS host:port endpoints for the advertised Stores' business RPCs.
	StoreEndpoints []string `protobuf:"bytes,6,rep,name=store_endpoints,json=storeEndpoints,proto3" json:"store_endpoints,omitempty"`
	// Remaining origin lease in milliseconds at the time this snapshot is formed.
	LeaseRemainingMs uint64 `protobuf:"varint,7,opt,name=lease_remaining_ms,json=leaseRemainingMs,proto3" json:"lease_remaining_ms,omitempty"`
	// Explicit process withdrawal; this incarnation must no longer supply endpoints.
	Withdrawn     bool `protobuf:"varint,8,opt,name=withdrawn,proto3" json:"withdrawn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAnnouncement) Reset() {
	*x = NodeAnnouncement{}
	mi := &file_internal_api_peer_v1_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAnnouncement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAnnouncement) ProtoMessage() {}

func (x *NodeAnnouncement) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_peer_v1_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAnnouncement.ProtoReflect.Descriptor instead.
func (*NodeAnnouncement) Descriptor() ([]byte, []int) {
	return file_internal_api_peer_v1_peer_proto_rawDescGZIP(), []int{2}
}

func (x *NodeAnnouncement) GetIncarnationId() string {
	if x != nil {
		return x.IncarnationId
	}
	return ""
}

func (x *NodeAnnouncement) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *NodeAnnouncement) GetPeerEndpoint() string {
	if x != nil {
		return x.PeerEndpoint
	}
	return ""
}

func (x *NodeAnnouncement) GetReplicaGroup() string {
	if x != nil {
		return x.ReplicaGroup
	}
	return ""
}

func (x *NodeAnnouncement) GetStoreNames() []string {
	if x != nil {
		return x.StoreNames
	}
	return nil
}

func (x *NodeAnnouncement) GetStoreEndpoints() []string {
	if x != nil {
		return x.StoreEndpoints
	}
	return nil
}

func (x *NodeAnnouncement) GetLeaseRemainingMs() uint64 {
	if x != nil {
		return x.LeaseRemainingMs
	}
	return 0
}

func (x *NodeAnnouncement) GetWithdrawn() bool {
	if x != nil {
		return x.Withdrawn
	}
	return false
}

var File_internal_api_peer_v1_peer_proto protoreflect.FileDescriptor

const file_internal_api_peer_v1_peer_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/api/peer/v1/peer.proto\x12\fweir.peer.v1\"\\\n" +
	"\x14SyncDirectoryRequest\x12D\n" +
	"\rannouncements\x18\x01 \x03(\v2\x1e.weir.peer.v1.NodeAnnouncementR\rannouncements\"]\n" +
	"\x15SyncDirectoryResponse\x12D\n" +
	"\rannouncements\x18\x01 \x03(\v2\x1e.weir.peer.v1.NodeAnnouncementR\rannouncements\"\xb5\x02\n" +
	"\x10NodeAnnouncement\x12%\n" +
	"\x0eincarnation_id\x18\x01 \x01(\tR\rincarnationId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12#\n" +
	"\rpeer_endpoint\x18\x03 \x01(\tR\fpeerEndpoint\x12#\n" +
	"\rreplica_group\x18\x04 \x01(\tR\freplicaGroup\x12\x1f\n" +
	"\vstore_names\x18\x05 \x03(\tR\n" +
	"storeNames\x12'\n" +
	"\x0fstore_endpoints\x18\x06 \x03(\tR\x0estoreEndpoints\x12,\n" +
	"\x12lease_remaining_ms\x18\a \x01(\x04R\x10leaseRemainingMs\x12\x1c\n" +
	"\twithdrawn\x18\b \x01(\bR\twithdrawn2p\n" +
	"\x14PeerDiscoveryService\x12X\n" +
	"\rSyncDirectory\x12\".weir.peer.v1.SyncDirectoryRequest\x1a#.weir.peer.v1.SyncDirectoryResponseB9Z7github.com/batchstream/weir/internal/api/peer/v1;peerv1b\x06proto3"

var (
	file_internal_api_peer_v1_peer_proto_rawDescOnce sync.Once
	file_internal_api_peer_v1_peer_proto_rawDescData []byte
)

func file_internal_api_peer_v1_peer_proto_rawDescGZIP() []byte {
	file_internal_api_peer_v1_peer_proto_rawDescOnce.Do(func() {
		file_internal_api_peer_v1_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_peer_v1_peer_proto_rawDesc), len(file_internal_api_peer_v1_peer_proto_rawDesc)))
	})
	return file_internal_api_peer_v1_peer_proto_rawDescData
}

var file_internal_api_peer_v1_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_api_peer_v1_peer_proto_goTypes = []any{
	(*SyncDirectoryRequest)(nil),  // 0: weir.peer.v1.SyncDirectoryRequest
	(*SyncDirectoryResponse)(nil), // 1: weir.peer.v1.SyncDirectoryResponse
	(*NodeAnnouncement)(nil),      // 2: weir.peer.v1.NodeAnnouncement
}
var file_internal_api_peer_v1_peer_proto_depIdxs = []int32{
	2, // 0: weir.peer.v1.SyncDirectoryRequest.announcements:type_name -> weir.peer.v1.NodeAnnouncement
	2, // 1: weir.peer.v1.SyncDirectoryResponse.announcements:type_name -> weir.peer.v1.NodeAnnouncement
	0, // 2: weir.peer.v1.PeerDiscoveryService.SyncDirectory:input_type -> weir.peer.v1.SyncDirectoryRequest
	1, // 3: weir.peer.v1.PeerDiscoveryService.SyncDirectory:output_type -> weir.peer.v1.SyncDirectoryResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_api_peer_v1_peer_proto_init() }
func file_internal_api_peer_v1_peer_proto_init() {
	if File_internal_api_peer_v1_peer_proto != nil {
		return
	}
	type x struct{}
	packageMarker := x{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(packageMarker).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_peer_v1_peer_proto_rawDesc), len(file_internal_api_peer_v1_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_api_peer_v1_peer_proto_goTypes,
		DependencyIndexes: file_internal_api_peer_v1_peer_proto_depIdxs,
		MessageInfos:      file_internal_api_peer_v1_peer_proto_msgTypes,
	}.Build()
	File_internal_api_peer_v1_peer_proto = out.File
	file_internal_api_peer_v1_peer_proto_goTypes = nil
	file_internal_api_peer_v1_peer_proto_depIdxs = nil
}
