"services":
  - "name": "database"
    "local":
      "max_concurrency": 4
      "max_batch_operations": 16
      "search":
        "url": "http://elasticsearch:9200"
      "batch_collect": "3ms"
      "max_read_size": "16KiB"
"routes":
  - "store": "records"
    "service": "database"
