// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: api/weir/v1/weir.proto

package weirv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Weir_Route_FullMethodName = "/weir.v1.Weir/Route"
)

// WeirClient is the client API for Weir service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// One finite stream fixes its logical Store on the first valid request.
type WeirClient interface {
	Route(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error)
}

type weirClient struct {
	cc grpc.ClientConnInterface
}

func NewWeirClient(cc grpc.ClientConnInterface) WeirClient {
	client := &weirClient{cc}
	return client
}

func (c *weirClient) Route(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Weir_ServiceDesc.Streams[0], Weir_Route_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Weir_RouteClient = grpc.BidiStreamingClient[Request, Response]

// WeirServer is the server API for Weir service.
// All implementations must embed UnimplementedWeirServer
// for forward compatibility.
//
// One finite stream fixes its logical Store on the first valid request.
type WeirServer interface {
	Route(grpc.BidiStreamingServer[Request, Response]) error
	mustEmbedUnimplementedWeirServer()
}

// UnimplementedWeirServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeirServer struct{}

func (UnimplementedWeirServer) Route(grpc.BidiStreamingServer[Request, Response]) error {
	return status.Errorf(codes.Unimplemented, "method Route not implemented")
}
func (UnimplementedWeirServer) mustEmbedUnimplementedWeirServer() {}
func (UnimplementedWeirServer) testEmbeddedByValue()              {}

// UnsafeWeirServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeirServer will
// result in compilation errors.
type UnsafeWeirServer interface {
	mustEmbedUnimplementedWeirServer()
}

func RegisterWeirServer(s grpc.ServiceRegistrar, srv WeirServer) {
	// If the following call pancis, it indicates UnimplementedWeirServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Weir_ServiceDesc, srv)
}

func _Weir_Route_Handler(srv interface{}, stream grpc.ServerStream) error {
	serverStream := &grpc.GenericServerStream[Request, Response]{ServerStream: stream}
	return srv.(WeirServer).Route(serverStream)
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Weir_RouteServer = grpc.BidiStreamingServer[Request, Response]

// Weir_ServiceDesc is the grpc.ServiceDesc for Weir service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Weir_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weir.v1.Weir",
	HandlerType: (*WeirServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Route",
			Handler:       _Weir_Route_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/weir/v1/weir.proto",
}
