// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: api/weir/v1/weir.proto

package weirv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Weir_Resolve_FullMethodName = "/weir.v1.Weir/Resolve"
	Weir_Route_FullMethodName   = "/weir.v1.Weir/Route"
)

// WeirClient is the client API for Weir service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// One finite stream fixes its logical Store on the first valid request.
type WeirClient interface {
	// Resolve discovers the group serving a Store before business data is sent.
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
	Route(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error)
}

type weirClient struct {
	cc grpc.ClientConnInterface
}

func NewWeirClient(cc grpc.ClientConnInterface) WeirClient {
	client := &weirClient{cc}
	return client
}

func (c *weirClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, Weir_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weirClient) Route(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Weir_ServiceDesc.Streams[0], Weir_Route_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Weir_RouteClient = grpc.BidiStreamingClient[Request, Response]

// WeirServer is the server API for Weir service.
// All implementations must embed UnimplementedWeirServer
// for forward compatibility.
//
// One finite stream fixes its logical Store on the first valid request.
type WeirServer interface {
	// Resolve discovers the group serving a Store before business data is sent.
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	Route(grpc.BidiStreamingServer[Request, Response]) error
	mustEmbedUnimplementedWeirServer()
}

// UnimplementedWeirServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeirServer struct{}

func (UnimplementedWeirServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedWeirServer) Route(grpc.BidiStreamingServer[Request, Response]) error {
	return status.Errorf(codes.Unimplemented, "method Route not implemented")
}
func (UnimplementedWeirServer) mustEmbedUnimplementedWeirServer() {}
func (UnimplementedWeirServer) testEmbeddedByValue()              {}

// UnsafeWeirServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeirServer will
// result in compilation errors.
type UnsafeWeirServer interface {
	mustEmbedUnimplementedWeirServer()
}

func RegisterWeirServer(s grpc.ServiceRegistrar, srv WeirServer) {
	// If the following call pancis, it indicates UnimplementedWeirServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Weir_ServiceDesc, srv)
}

func _Weir_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeirServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Weir_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeirServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Weir_Route_Handler(srv interface{}, stream grpc.ServerStream) error {
	serverStream := &grpc.GenericServerStream[Request, Response]{ServerStream: stream}
	return srv.(WeirServer).Route(serverStream)
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Weir_RouteServer = grpc.BidiStreamingServer[Request, Response]

// Weir_ServiceDesc is the grpc.ServiceDesc for Weir service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Weir_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weir.v1.Weir",
	HandlerType: (*WeirServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _Weir_Resolve_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Route",
			Handler:       _Weir_Route_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/weir/v1/weir.proto",
}

const (
	Directory_Exchange_FullMethodName = "/weir.v1.Directory/Exchange"
)

// DirectoryClient is the client API for Directory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Directory is a peer-only control service. It never transports business data.
type DirectoryClient interface {
	Exchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*ExchangeResponse, error)
}

type directoryClient struct {
	cc grpc.ClientConnInterface
}

func NewDirectoryClient(cc grpc.ClientConnInterface) DirectoryClient {
	client := &directoryClient{cc}
	return client
}

func (c *directoryClient) Exchange(ctx context.Context, in *ExchangeRequest, opts ...grpc.CallOption) (*ExchangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeResponse)
	err := c.cc.Invoke(ctx, Directory_Exchange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DirectoryServer is the server API for Directory service.
// All implementations must embed UnimplementedDirectoryServer
// for forward compatibility.
//
// Directory is a peer-only control service. It never transports business data.
type DirectoryServer interface {
	Exchange(context.Context, *ExchangeRequest) (*ExchangeResponse, error)
	mustEmbedUnimplementedDirectoryServer()
}

// UnimplementedDirectoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDirectoryServer struct{}

func (UnimplementedDirectoryServer) Exchange(context.Context, *ExchangeRequest) (*ExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exchange not implemented")
}
func (UnimplementedDirectoryServer) mustEmbedUnimplementedDirectoryServer() {}
func (UnimplementedDirectoryServer) testEmbeddedByValue()                   {}

// UnsafeDirectoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DirectoryServer will
// result in compilation errors.
type UnsafeDirectoryServer interface {
	mustEmbedUnimplementedDirectoryServer()
}

func RegisterDirectoryServer(s grpc.ServiceRegistrar, srv DirectoryServer) {
	// If the following call pancis, it indicates UnimplementedDirectoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Directory_ServiceDesc, srv)
}

func _Directory_Exchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DirectoryServer).Exchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Directory_Exchange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DirectoryServer).Exchange(ctx, req.(*ExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Directory_ServiceDesc is the grpc.ServiceDesc for Directory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Directory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weir.v1.Directory",
	HandlerType: (*DirectoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exchange",
			Handler:    _Directory_Exchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/weir/v1/weir.proto",
}
