// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: api/weir/v1/weir.proto

package weirv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Weir_Read_FullMethodName   = "/weir.v1.Weir/Read"
	Weir_Mutate_FullMethodName = "/weir.v1.Weir/Mutate"
	Weir_Bulk_FullMethodName   = "/weir.v1.Weir/Bulk"
)

// WeirClient is the client API for Weir service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeirClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResult, error)
	Mutate(ctx context.Context, in *MutateRequest, opts ...grpc.CallOption) (*MutationResult, error)
	Bulk(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BulkRequestFrame, BulkResponseFrame], error)
}

type weirClient struct {
	cc grpc.ClientConnInterface
}

func NewWeirClient(cc grpc.ClientConnInterface) WeirClient {
	client := &weirClient{cc}
	return client
}

func (c *weirClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResult)
	err := c.cc.Invoke(ctx, Weir_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weirClient) Mutate(ctx context.Context, in *MutateRequest, opts ...grpc.CallOption) (*MutationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResult)
	err := c.cc.Invoke(ctx, Weir_Mutate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weirClient) Bulk(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BulkRequestFrame, BulkResponseFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Weir_ServiceDesc.Streams[0], Weir_Bulk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BulkRequestFrame, BulkResponseFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Weir_BulkClient = grpc.BidiStreamingClient[BulkRequestFrame, BulkResponseFrame]

// WeirServer is the server API for Weir service.
// All implementations must embed UnimplementedWeirServer
// for forward compatibility.
type WeirServer interface {
	Read(context.Context, *ReadRequest) (*ReadResult, error)
	Mutate(context.Context, *MutateRequest) (*MutationResult, error)
	Bulk(grpc.BidiStreamingServer[BulkRequestFrame, BulkResponseFrame]) error
	mustEmbedUnimplementedWeirServer()
}

// UnimplementedWeirServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeirServer struct{}

func (UnimplementedWeirServer) Read(context.Context, *ReadRequest) (*ReadResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedWeirServer) Mutate(context.Context, *MutateRequest) (*MutationResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mutate not implemented")
}
func (UnimplementedWeirServer) Bulk(grpc.BidiStreamingServer[BulkRequestFrame, BulkResponseFrame]) error {
	return status.Errorf(codes.Unimplemented, "method Bulk not implemented")
}
func (UnimplementedWeirServer) mustEmbedUnimplementedWeirServer() {}
func (UnimplementedWeirServer) testEmbeddedByValue()              {}

// UnsafeWeirServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeirServer will
// result in compilation errors.
type UnsafeWeirServer interface {
	mustEmbedUnimplementedWeirServer()
}

func RegisterWeirServer(s grpc.ServiceRegistrar, srv WeirServer) {
	// If the following call pancis, it indicates UnimplementedWeirServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Weir_ServiceDesc, srv)
}

func _Weir_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeirServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Weir_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeirServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Weir_Mutate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeirServer).Mutate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Weir_Mutate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeirServer).Mutate(ctx, req.(*MutateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Weir_Bulk_Handler(srv interface{}, stream grpc.ServerStream) error {
	serverStream := &grpc.GenericServerStream[BulkRequestFrame, BulkResponseFrame]{ServerStream: stream}
	return srv.(WeirServer).Bulk(serverStream)
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Weir_BulkServer = grpc.BidiStreamingServer[BulkRequestFrame, BulkResponseFrame]

// Weir_ServiceDesc is the grpc.ServiceDesc for Weir service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Weir_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weir.v1.Weir",
	HandlerType: (*WeirServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Weir_Read_Handler,
		},
		{
			MethodName: "Mutate",
			Handler:    _Weir_Mutate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Bulk",
			Handler:       _Weir_Bulk_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/weir/v1/weir.proto",
}
