// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/weir/v1/weir.proto

package weirv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FailureCode int32

const (
	FailureCode_FAILURE_CODE_UNSPECIFIED FailureCode = 0
	FailureCode_INVALID_ARGUMENT         FailureCode = 1
	FailureCode_UNAUTHENTICATED          FailureCode = 2
	FailureCode_PERMISSION_DENIED        FailureCode = 3
	FailureCode_NOT_FOUND                FailureCode = 4
	FailureCode_PRECONDITION_FAILED      FailureCode = 5
	FailureCode_CONFLICT                 FailureCode = 6
	FailureCode_UNSUPPORTED              FailureCode = 7
	FailureCode_RESOURCE_EXHAUSTED       FailureCode = 8
	FailureCode_UNAVAILABLE              FailureCode = 9
	FailureCode_CANCELLED                FailureCode = 10
	FailureCode_DEADLINE_EXCEEDED        FailureCode = 11
	FailureCode_INTERNAL                 FailureCode = 12
)

// Enum value maps for FailureCode.
var (
	FailureCode_name = map[int32]string{
		0:  "FAILURE_CODE_UNSPECIFIED",
		1:  "INVALID_ARGUMENT",
		2:  "UNAUTHENTICATED",
		3:  "PERMISSION_DENIED",
		4:  "NOT_FOUND",
		5:  "PRECONDITION_FAILED",
		6:  "CONFLICT",
		7:  "UNSUPPORTED",
		8:  "RESOURCE_EXHAUSTED",
		9:  "UNAVAILABLE",
		10: "CANCELLED",
		11: "DEADLINE_EXCEEDED",
		12: "INTERNAL",
	}
	FailureCode_value = map[string]int32{
		"FAILURE_CODE_UNSPECIFIED": 0,
		"INVALID_ARGUMENT":         1,
		"UNAUTHENTICATED":          2,
		"PERMISSION_DENIED":        3,
		"NOT_FOUND":                4,
		"PRECONDITION_FAILED":      5,
		"CONFLICT":                 6,
		"UNSUPPORTED":              7,
		"RESOURCE_EXHAUSTED":       8,
		"UNAVAILABLE":              9,
		"CANCELLED":                10,
		"DEADLINE_EXCEEDED":        11,
		"INTERNAL":                 12,
	}
)

func (x FailureCode) Enum() *FailureCode {
	p := new(FailureCode)
	*p = x
	return p
}

func (x FailureCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_weir_v1_weir_proto_enumTypes[0].Descriptor()
}

func (FailureCode) Type() protoreflect.EnumType {
	return &file_api_weir_v1_weir_proto_enumTypes[0]
}

func (x FailureCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureCode.Descriptor instead.
func (FailureCode) EnumDescriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{0}
}

type MutationOutcome int32

const (
	MutationOutcome_MUTATION_OUTCOME_UNSPECIFIED MutationOutcome = 0
	MutationOutcome_NOT_STARTED                  MutationOutcome = 1
	MutationOutcome_NOT_APPLIED                  MutationOutcome = 2
	MutationOutcome_APPLIED                      MutationOutcome = 3
	MutationOutcome_UNKNOWN                      MutationOutcome = 4
)

// Enum value maps for MutationOutcome.
var (
	MutationOutcome_name = map[int32]string{
		0: "MUTATION_OUTCOME_UNSPECIFIED",
		1: "NOT_STARTED",
		2: "NOT_APPLIED",
		3: "APPLIED",
		4: "UNKNOWN",
	}
	MutationOutcome_value = map[string]int32{
		"MUTATION_OUTCOME_UNSPECIFIED": 0,
		"NOT_STARTED":                  1,
		"NOT_APPLIED":                  2,
		"APPLIED":                      3,
		"UNKNOWN":                      4,
	}
)

func (x MutationOutcome) Enum() *MutationOutcome {
	p := new(MutationOutcome)
	*p = x
	return p
}

func (x MutationOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_api_weir_v1_weir_proto_enumTypes[1].Descriptor()
}

func (MutationOutcome) Type() protoreflect.EnumType {
	return &file_api_weir_v1_weir_proto_enumTypes[1]
}

func (x MutationOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutationOutcome.Descriptor instead.
func (MutationOutcome) EnumDescriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{0}
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaType     string                 `protobuf:"bytes,1,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{1}
}

func (x *Document) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Document) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          FailureCode            `protobuf:"varint,1,opt,name=code,proto3,enum=weir.v1.FailureCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{2}
}

func (x *Failure) GetCode() FailureCode {
	if x != nil {
		return x.Code
	}
	return FailureCode_FAILURE_CODE_UNSPECIFIED
}

func (x *Failure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Resource       string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	ReadMediaType  string                 `protobuf:"bytes,2,opt,name=read_media_type,json=readMediaType,proto3" json:"read_media_type,omitempty"`
	AdapterOptions *Document              `protobuf:"bytes,3,opt,name=adapter_options,json=adapterOptions,proto3" json:"adapter_options,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{3}
}

func (x *ReadRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ReadRequest) GetReadMediaType() string {
	if x != nil {
		return x.ReadMediaType
	}
	return ""
}

func (x *ReadRequest) GetAdapterOptions() *Document {
	if x != nil {
		return x.AdapterOptions
	}
	return nil
}

type ReadResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ReadResult_Document
	//	*ReadResult_Missing
	//	*ReadResult_Failure
	Result        isReadResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResult) Reset() {
	*x = ReadResult{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResult) ProtoMessage() {}

func (x *ReadResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResult.ProtoReflect.Descriptor instead.
func (*ReadResult) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{4}
}

func (x *ReadResult) GetResult() isReadResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ReadResult) GetDocument() *Document {
	if x != nil {
		if x, ok := x.Result.(*ReadResult_Document); ok {
			return x.Document
		}
	}
	return nil
}

func (x *ReadResult) GetMissing() *Empty {
	if x != nil {
		if x, ok := x.Result.(*ReadResult_Missing); ok {
			return x.Missing
		}
	}
	return nil
}

func (x *ReadResult) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Result.(*ReadResult_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isReadResult_Result interface {
	isReadResult_Result()
}

type ReadResult_Document struct {
	Document *Document `protobuf:"bytes,1,opt,name=document,proto3,oneof"`
}

type ReadResult_Missing struct {
	Missing *Empty `protobuf:"bytes,2,opt,name=missing,proto3,oneof"`
}

type ReadResult_Failure struct {
	Failure *Failure `protobuf:"bytes,3,opt,name=failure,proto3,oneof"`
}

func (*ReadResult_Document) isReadResult_Result() {}

func (*ReadResult_Missing) isReadResult_Result() {}

func (*ReadResult_Failure) isReadResult_Result() {}

type MutateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Resource       string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	AdapterOptions *Document              `protobuf:"bytes,2,opt,name=adapter_options,json=adapterOptions,proto3" json:"adapter_options,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*MutateRequest_Put
	//	*MutateRequest_Create
	//	*MutateRequest_Replace
	//	*MutateRequest_Delete
	//	*MutateRequest_AtomicTransform
	Action        isMutateRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateRequest) Reset() {
	*x = MutateRequest{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateRequest) ProtoMessage() {}

func (x *MutateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateRequest.ProtoReflect.Descriptor instead.
func (*MutateRequest) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{5}
}

func (x *MutateRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *MutateRequest) GetAdapterOptions() *Document {
	if x != nil {
		return x.AdapterOptions
	}
	return nil
}

func (x *MutateRequest) GetAction() isMutateRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *MutateRequest) GetPut() *Document {
	if x != nil {
		if x, ok := x.Action.(*MutateRequest_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *MutateRequest) GetCreate() *Document {
	if x != nil {
		if x, ok := x.Action.(*MutateRequest_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *MutateRequest) GetReplace() *Document {
	if x != nil {
		if x, ok := x.Action.(*MutateRequest_Replace); ok {
			return x.Replace
		}
	}
	return nil
}

func (x *MutateRequest) GetDelete() *Empty {
	if x != nil {
		if x, ok := x.Action.(*MutateRequest_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *MutateRequest) GetAtomicTransform() *Transform {
	if x != nil {
		if x, ok := x.Action.(*MutateRequest_AtomicTransform); ok {
			return x.AtomicTransform
		}
	}
	return nil
}

type isMutateRequest_Action interface {
	isMutateRequest_Action()
}

type MutateRequest_Put struct {
	Put *Document `protobuf:"bytes,10,opt,name=put,proto3,oneof"`
}

type MutateRequest_Create struct {
	Create *Document `protobuf:"bytes,11,opt,name=create,proto3,oneof"`
}

type MutateRequest_Replace struct {
	Replace *Document `protobuf:"bytes,12,opt,name=replace,proto3,oneof"`
}

type MutateRequest_Delete struct {
	Delete *Empty `protobuf:"bytes,13,opt,name=delete,proto3,oneof"`
}

type MutateRequest_AtomicTransform struct {
	AtomicTransform *Transform `protobuf:"bytes,14,opt,name=atomic_transform,json=atomicTransform,proto3,oneof"`
}

func (*MutateRequest_Put) isMutateRequest_Action() {}

func (*MutateRequest_Create) isMutateRequest_Action() {}

func (*MutateRequest_Replace) isMutateRequest_Action() {}

func (*MutateRequest_Delete) isMutateRequest_Action() {}

func (*MutateRequest_AtomicTransform) isMutateRequest_Action() {}

type MutationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       MutationOutcome        `protobuf:"varint,1,opt,name=outcome,proto3,enum=weir.v1.MutationOutcome" json:"outcome,omitempty"`
	Failure       *Failure               `protobuf:"bytes,2,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationResult) Reset() {
	*x = MutationResult{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationResult) ProtoMessage() {}

func (x *MutationResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationResult.ProtoReflect.Descriptor instead.
func (*MutationResult) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{6}
}

func (x *MutationResult) GetOutcome() MutationOutcome {
	if x != nil {
		return x.Outcome
	}
	return MutationOutcome_MUTATION_OUTCOME_UNSPECIFIED
}

func (x *MutationResult) GetFailure() *Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type Transform struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Form:
	//
	//	*Transform_Program
	//	*Transform_BackendExpression
	Form          isTransform_Form `protobuf_oneof:"form"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transform) Reset() {
	*x = Transform{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transform) ProtoMessage() {}

func (x *Transform) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transform.ProtoReflect.Descriptor instead.
func (*Transform) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{7}
}

func (x *Transform) GetForm() isTransform_Form {
	if x != nil {
		return x.Form
	}
	return nil
}

func (x *Transform) GetProgram() *ProgramTransform {
	if x != nil {
		if x, ok := x.Form.(*Transform_Program); ok {
			return x.Program
		}
	}
	return nil
}

func (x *Transform) GetBackendExpression() *Document {
	if x != nil {
		if x, ok := x.Form.(*Transform_BackendExpression); ok {
			return x.BackendExpression
		}
	}
	return nil
}

type isTransform_Form interface {
	isTransform_Form()
}

type Transform_Program struct {
	Program *ProgramTransform `protobuf:"bytes,1,opt,name=program,proto3,oneof"`
}

type Transform_BackendExpression struct {
	BackendExpression *Document `protobuf:"bytes,2,opt,name=backend_expression,json=backendExpression,proto3,oneof"`
}

func (*Transform_Program) isTransform_Form() {}

func (*Transform_BackendExpression) isTransform_Form() {}

type ProgramTransform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       string                 `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Source        []byte                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Input         *Document              `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramTransform) Reset() {
	*x = ProgramTransform{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramTransform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramTransform) ProtoMessage() {}

func (x *ProgramTransform) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramTransform.ProtoReflect.Descriptor instead.
func (*ProgramTransform) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{8}
}

func (x *ProgramTransform) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *ProgramTransform) GetSource() []byte {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ProgramTransform) GetInput() *Document {
	if x != nil {
		return x.Input
	}
	return nil
}

type BulkOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkOpen) Reset() {
	*x = BulkOpen{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkOpen) ProtoMessage() {}

func (x *BulkOpen) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkOpen.ProtoReflect.Descriptor instead.
func (*BulkOpen) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{9}
}

func (x *BulkOpen) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

type BulkOperation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*BulkOperation_Read
	//	*BulkOperation_Mutate
	Operation     isBulkOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkOperation) Reset() {
	*x = BulkOperation{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkOperation) ProtoMessage() {}

func (x *BulkOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkOperation.ProtoReflect.Descriptor instead.
func (*BulkOperation) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{10}
}

func (x *BulkOperation) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BulkOperation) GetOperation() isBulkOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *BulkOperation) GetRead() *ReadRequest {
	if x != nil {
		if x, ok := x.Operation.(*BulkOperation_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *BulkOperation) GetMutate() *MutateRequest {
	if x != nil {
		if x, ok := x.Operation.(*BulkOperation_Mutate); ok {
			return x.Mutate
		}
	}
	return nil
}

type isBulkOperation_Operation interface {
	isBulkOperation_Operation()
}

type BulkOperation_Read struct {
	Read *ReadRequest `protobuf:"bytes,10,opt,name=read,proto3,oneof"`
}

type BulkOperation_Mutate struct {
	Mutate *MutateRequest `protobuf:"bytes,11,opt,name=mutate,proto3,oneof"`
}

func (*BulkOperation_Read) isBulkOperation_Operation() {}

func (*BulkOperation_Mutate) isBulkOperation_Operation() {}

type BulkRequestFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*BulkRequestFrame_Open
	//	*BulkRequestFrame_Operation
	Frame         isBulkRequestFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkRequestFrame) Reset() {
	*x = BulkRequestFrame{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkRequestFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkRequestFrame) ProtoMessage() {}

func (x *BulkRequestFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkRequestFrame.ProtoReflect.Descriptor instead.
func (*BulkRequestFrame) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{11}
}

func (x *BulkRequestFrame) GetFrame() isBulkRequestFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *BulkRequestFrame) GetOpen() *BulkOpen {
	if x != nil {
		if x, ok := x.Frame.(*BulkRequestFrame_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *BulkRequestFrame) GetOperation() *BulkOperation {
	if x != nil {
		if x, ok := x.Frame.(*BulkRequestFrame_Operation); ok {
			return x.Operation
		}
	}
	return nil
}

type isBulkRequestFrame_Frame interface {
	isBulkRequestFrame_Frame()
}

type BulkRequestFrame_Open struct {
	Open *BulkOpen `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type BulkRequestFrame_Operation struct {
	Operation *BulkOperation `protobuf:"bytes,2,opt,name=operation,proto3,oneof"`
}

func (*BulkRequestFrame_Open) isBulkRequestFrame_Frame() {}

func (*BulkRequestFrame_Operation) isBulkRequestFrame_Frame() {}

type BulkResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*BulkResult_Read
	//	*BulkResult_Mutation
	Result        isBulkResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkResult) Reset() {
	*x = BulkResult{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkResult) ProtoMessage() {}

func (x *BulkResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkResult.ProtoReflect.Descriptor instead.
func (*BulkResult) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{12}
}

func (x *BulkResult) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BulkResult) GetResult() isBulkResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BulkResult) GetRead() *ReadResult {
	if x != nil {
		if x, ok := x.Result.(*BulkResult_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *BulkResult) GetMutation() *MutationResult {
	if x != nil {
		if x, ok := x.Result.(*BulkResult_Mutation); ok {
			return x.Mutation
		}
	}
	return nil
}

type isBulkResult_Result interface {
	isBulkResult_Result()
}

type BulkResult_Read struct {
	Read *ReadResult `protobuf:"bytes,10,opt,name=read,proto3,oneof"`
}

type BulkResult_Mutation struct {
	Mutation *MutationResult `protobuf:"bytes,11,opt,name=mutation,proto3,oneof"`
}

func (*BulkResult_Read) isBulkResult_Result() {}

func (*BulkResult_Mutation) isBulkResult_Result() {}

type BulkEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceivedCount uint64                 `protobuf:"varint,1,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"`
	ResultCount   uint64                 `protobuf:"varint,2,opt,name=result_count,json=resultCount,proto3" json:"result_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkEnd) Reset() {
	*x = BulkEnd{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkEnd) ProtoMessage() {}

func (x *BulkEnd) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkEnd.ProtoReflect.Descriptor instead.
func (*BulkEnd) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{13}
}

func (x *BulkEnd) GetReceivedCount() uint64 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

func (x *BulkEnd) GetResultCount() uint64 {
	if x != nil {
		return x.ResultCount
	}
	return 0
}

type BulkResponseFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*BulkResponseFrame_Result
	//	*BulkResponseFrame_End
	Frame         isBulkResponseFrame_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkResponseFrame) Reset() {
	*x = BulkResponseFrame{}
	mi := &file_api_weir_v1_weir_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkResponseFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkResponseFrame) ProtoMessage() {}

func (x *BulkResponseFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_weir_v1_weir_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkResponseFrame.ProtoReflect.Descriptor instead.
func (*BulkResponseFrame) Descriptor() ([]byte, []int) {
	return file_api_weir_v1_weir_proto_rawDescGZIP(), []int{14}
}

func (x *BulkResponseFrame) GetFrame() isBulkResponseFrame_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *BulkResponseFrame) GetResult() *BulkResult {
	if x != nil {
		if x, ok := x.Frame.(*BulkResponseFrame_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *BulkResponseFrame) GetEnd() *BulkEnd {
	if x != nil {
		if x, ok := x.Frame.(*BulkResponseFrame_End); ok {
			return x.End
		}
	}
	return nil
}

type isBulkResponseFrame_Frame interface {
	isBulkResponseFrame_Frame()
}

type BulkResponseFrame_Result struct {
	Result *BulkResult `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
}

type BulkResponseFrame_End struct {
	End *BulkEnd `protobuf:"bytes,2,opt,name=end,proto3,oneof"`
}

func (*BulkResponseFrame_Result) isBulkResponseFrame_Frame() {}

func (*BulkResponseFrame_End) isBulkResponseFrame_Frame() {}

var File_api_weir_v1_weir_proto protoreflect.FileDescriptor

const file_api_weir_v1_weir_proto_rawDesc = "" +
	"\n" +
	"\x16api/weir/v1/weir.proto\x12\aweir.v1\"\a\n" +
	"\x05Empty\"=\n" +
	"\bDocument\x12\x1d\n" +
	"\n" +
	"media_type\x18\x01 \x01(\tR\tmediaType\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"M\n" +
	"\aFailure\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.weir.v1.FailureCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8d\x01\n" +
	"\vReadRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12&\n" +
	"\x0fread_media_type\x18\x02 \x01(\tR\rreadMediaType\x12:\n" +
	"\x0fadapter_options\x18\x03 \x01(\v2\x11.weir.v1.DocumentR\x0eadapterOptions\"\xa1\x01\n" +
	"\n" +
	"ReadResult\x12/\n" +
	"\bdocument\x18\x01 \x01(\v2\x11.weir.v1.DocumentH\x00R\bdocument\x12*\n" +
	"\amissing\x18\x02 \x01(\v2\x0e.weir.v1.EmptyH\x00R\amissing\x12,\n" +
	"\afailure\x18\x03 \x01(\v2\x10.weir.v1.FailureH\x00R\afailureB\b\n" +
	"\x06result\"\xdf\x02\n" +
	"\rMutateRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12:\n" +
	"\x0fadapter_options\x18\x02 \x01(\v2\x11.weir.v1.DocumentR\x0eadapterOptions\x12%\n" +
	"\x03put\x18\n" +
	" \x01(\v2\x11.weir.v1.DocumentH\x00R\x03put\x12+\n" +
	"\x06create\x18\v \x01(\v2\x11.weir.v1.DocumentH\x00R\x06create\x12-\n" +
	"\areplace\x18\f \x01(\v2\x11.weir.v1.DocumentH\x00R\areplace\x12(\n" +
	"\x06delete\x18\r \x01(\v2\x0e.weir.v1.EmptyH\x00R\x06delete\x12?\n" +
	"\x10atomic_transform\x18\x0e \x01(\v2\x12.weir.v1.TransformH\x00R\x0fatomicTransformB\b\n" +
	"\x06action\"p\n" +
	"\x0eMutationResult\x122\n" +
	"\aoutcome\x18\x01 \x01(\x0e2\x18.weir.v1.MutationOutcomeR\aoutcome\x12*\n" +
	"\afailure\x18\x02 \x01(\v2\x10.weir.v1.FailureR\afailure\"\x8e\x01\n" +
	"\tTransform\x125\n" +
	"\aprogram\x18\x01 \x01(\v2\x19.weir.v1.ProgramTransformH\x00R\aprogram\x12B\n" +
	"\x12backend_expression\x18\x02 \x01(\v2\x11.weir.v1.DocumentH\x00R\x11backendExpressionB\x06\n" +
	"\x04form\"m\n" +
	"\x10ProgramTransform\x12\x18\n" +
	"\aruntime\x18\x01 \x01(\tR\aruntime\x12\x16\n" +
	"\x06source\x18\x02 \x01(\fR\x06source\x12'\n" +
	"\x05input\x18\x03 \x01(\v2\x11.weir.v1.DocumentR\x05input\" \n" +
	"\bBulkOpen\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\"\x90\x01\n" +
	"\rBulkOperation\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12*\n" +
	"\x04read\x18\n" +
	" \x01(\v2\x14.weir.v1.ReadRequestH\x00R\x04read\x120\n" +
	"\x06mutate\x18\v \x01(\v2\x16.weir.v1.MutateRequestH\x00R\x06mutateB\v\n" +
	"\toperation\"|\n" +
	"\x10BulkRequestFrame\x12'\n" +
	"\x04open\x18\x01 \x01(\v2\x11.weir.v1.BulkOpenH\x00R\x04open\x126\n" +
	"\toperation\x18\x02 \x01(\v2\x16.weir.v1.BulkOperationH\x00R\toperationB\a\n" +
	"\x05frame\"\x8e\x01\n" +
	"\n" +
	"BulkResult\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12)\n" +
	"\x04read\x18\n" +
	" \x01(\v2\x13.weir.v1.ReadResultH\x00R\x04read\x125\n" +
	"\bmutation\x18\v \x01(\v2\x17.weir.v1.MutationResultH\x00R\bmutationB\b\n" +
	"\x06result\"S\n" +
	"\aBulkEnd\x12%\n" +
	"\x0ereceived_count\x18\x01 \x01(\x04R\rreceivedCount\x12!\n" +
	"\fresult_count\x18\x02 \x01(\x04R\vresultCount\"q\n" +
	"\x11BulkResponseFrame\x12-\n" +
	"\x06result\x18\x01 \x01(\v2\x13.weir.v1.BulkResultH\x00R\x06result\x12$\n" +
	"\x03end\x18\x02 \x01(\v2\x10.weir.v1.BulkEndH\x00R\x03endB\a\n" +
	"\x05frame*\x91\x02\n" +
	"\vFailureCode\x12\x1c\n" +
	"\x18FAILURE_CODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x01\x12\x13\n" +
	"\x0fUNAUTHENTICATED\x10\x02\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\x03\x12\r\n" +
	"\tNOT_FOUND\x10\x04\x12\x17\n" +
	"\x13PRECONDITION_FAILED\x10\x05\x12\f\n" +
	"\bCONFLICT\x10\x06\x12\x0f\n" +
	"\vUNSUPPORTED\x10\a\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\b\x12\x0f\n" +
	"\vUNAVAILABLE\x10\t\x12\r\n" +
	"\tCANCELLED\x10\n" +
	"\x12\x15\n" +
	"\x11DEADLINE_EXCEEDED\x10\v\x12\f\n" +
	"\bINTERNAL\x10\f*o\n" +
	"\x0fMutationOutcome\x12 \n" +
	"\x1cMUTATION_OUTCOME_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vNOT_STARTED\x10\x01\x12\x0f\n" +
	"\vNOT_APPLIED\x10\x02\x12\v\n" +
	"\aAPPLIED\x10\x03\x12\v\n" +
	"\aUNKNOWN\x10\x042\xb7\x01\n" +
	"\x04Weir\x121\n" +
	"\x04Read\x12\x14.weir.v1.ReadRequest\x1a\x13.weir.v1.ReadResult\x129\n" +
	"\x06Mutate\x12\x16.weir.v1.MutateRequest\x1a\x17.weir.v1.MutationResult\x12A\n" +
	"\x04Bulk\x12\x19.weir.v1.BulkRequestFrame\x1a\x1a.weir.v1.BulkResponseFrame(\x010\x01B0Z.github.com/batchstream/weir/api/weir/v1;weirv1b\x06proto3"

var (
	file_api_weir_v1_weir_proto_rawDescOnce sync.Once
	file_api_weir_v1_weir_proto_rawDescData []byte
)

func file_api_weir_v1_weir_proto_rawDescGZIP() []byte {
	file_api_weir_v1_weir_proto_rawDescOnce.Do(func() {
		file_api_weir_v1_weir_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_weir_v1_weir_proto_rawDesc), len(file_api_weir_v1_weir_proto_rawDesc)))
	})
	return file_api_weir_v1_weir_proto_rawDescData
}

var file_api_weir_v1_weir_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_weir_v1_weir_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_weir_v1_weir_proto_goTypes = []any{
	(FailureCode)(0),          // 0: weir.v1.FailureCode
	(MutationOutcome)(0),      // 1: weir.v1.MutationOutcome
	(*Empty)(nil),             // 2: weir.v1.Empty
	(*Document)(nil),          // 3: weir.v1.Document
	(*Failure)(nil),           // 4: weir.v1.Failure
	(*ReadRequest)(nil),       // 5: weir.v1.ReadRequest
	(*ReadResult)(nil),        // 6: weir.v1.ReadResult
	(*MutateRequest)(nil),     // 7: weir.v1.MutateRequest
	(*MutationResult)(nil),    // 8: weir.v1.MutationResult
	(*Transform)(nil),         // 9: weir.v1.Transform
	(*ProgramTransform)(nil),  // 10: weir.v1.ProgramTransform
	(*BulkOpen)(nil),          // 11: weir.v1.BulkOpen
	(*BulkOperation)(nil),     // 12: weir.v1.BulkOperation
	(*BulkRequestFrame)(nil),  // 13: weir.v1.BulkRequestFrame
	(*BulkResult)(nil),        // 14: weir.v1.BulkResult
	(*BulkEnd)(nil),           // 15: weir.v1.BulkEnd
	(*BulkResponseFrame)(nil), // 16: weir.v1.BulkResponseFrame
}
var file_api_weir_v1_weir_proto_depIdxs = []int32{
	0,  // 0: weir.v1.Failure.code:type_name -> weir.v1.FailureCode
	3,  // 1: weir.v1.ReadRequest.adapter_options:type_name -> weir.v1.Document
	3,  // 2: weir.v1.ReadResult.document:type_name -> weir.v1.Document
	2,  // 3: weir.v1.ReadResult.missing:type_name -> weir.v1.Empty
	4,  // 4: weir.v1.ReadResult.failure:type_name -> weir.v1.Failure
	3,  // 5: weir.v1.MutateRequest.adapter_options:type_name -> weir.v1.Document
	3,  // 6: weir.v1.MutateRequest.put:type_name -> weir.v1.Document
	3,  // 7: weir.v1.MutateRequest.create:type_name -> weir.v1.Document
	3,  // 8: weir.v1.MutateRequest.replace:type_name -> weir.v1.Document
	2,  // 9: weir.v1.MutateRequest.delete:type_name -> weir.v1.Empty
	9,  // 10: weir.v1.MutateRequest.atomic_transform:type_name -> weir.v1.Transform
	1,  // 11: weir.v1.MutationResult.outcome:type_name -> weir.v1.MutationOutcome
	4,  // 12: weir.v1.MutationResult.failure:type_name -> weir.v1.Failure
	10, // 13: weir.v1.Transform.program:type_name -> weir.v1.ProgramTransform
	3,  // 14: weir.v1.Transform.backend_expression:type_name -> weir.v1.Document
	3,  // 15: weir.v1.ProgramTransform.input:type_name -> weir.v1.Document
	5,  // 16: weir.v1.BulkOperation.read:type_name -> weir.v1.ReadRequest
	7,  // 17: weir.v1.BulkOperation.mutate:type_name -> weir.v1.MutateRequest
	11, // 18: weir.v1.BulkRequestFrame.open:type_name -> weir.v1.BulkOpen
	12, // 19: weir.v1.BulkRequestFrame.operation:type_name -> weir.v1.BulkOperation
	6,  // 20: weir.v1.BulkResult.read:type_name -> weir.v1.ReadResult
	8,  // 21: weir.v1.BulkResult.mutation:type_name -> weir.v1.MutationResult
	14, // 22: weir.v1.BulkResponseFrame.result:type_name -> weir.v1.BulkResult
	15, // 23: weir.v1.BulkResponseFrame.end:type_name -> weir.v1.BulkEnd
	5,  // 24: weir.v1.Weir.Read:input_type -> weir.v1.ReadRequest
	7,  // 25: weir.v1.Weir.Mutate:input_type -> weir.v1.MutateRequest
	13, // 26: weir.v1.Weir.Bulk:input_type -> weir.v1.BulkRequestFrame
	6,  // 27: weir.v1.Weir.Read:output_type -> weir.v1.ReadResult
	8,  // 28: weir.v1.Weir.Mutate:output_type -> weir.v1.MutationResult
	16, // 29: weir.v1.Weir.Bulk:output_type -> weir.v1.BulkResponseFrame
	27, // [27:30] is the sub-list for method output_type
	24, // [24:27] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_api_weir_v1_weir_proto_init() }
func file_api_weir_v1_weir_proto_init() {
	if File_api_weir_v1_weir_proto != nil {
		return
	}
	file_api_weir_v1_weir_proto_msgTypes[4].OneofWrappers = []any{
		(*ReadResult_Document)(nil),
		(*ReadResult_Missing)(nil),
		(*ReadResult_Failure)(nil),
	}
	file_api_weir_v1_weir_proto_msgTypes[5].OneofWrappers = []any{
		(*MutateRequest_Put)(nil),
		(*MutateRequest_Create)(nil),
		(*MutateRequest_Replace)(nil),
		(*MutateRequest_Delete)(nil),
		(*MutateRequest_AtomicTransform)(nil),
	}
	file_api_weir_v1_weir_proto_msgTypes[7].OneofWrappers = []any{
		(*Transform_Program)(nil),
		(*Transform_BackendExpression)(nil),
	}
	file_api_weir_v1_weir_proto_msgTypes[10].OneofWrappers = []any{
		(*BulkOperation_Read)(nil),
		(*BulkOperation_Mutate)(nil),
	}
	file_api_weir_v1_weir_proto_msgTypes[11].OneofWrappers = []any{
		(*BulkRequestFrame_Open)(nil),
		(*BulkRequestFrame_Operation)(nil),
	}
	file_api_weir_v1_weir_proto_msgTypes[12].OneofWrappers = []any{
		(*BulkResult_Read)(nil),
		(*BulkResult_Mutation)(nil),
	}
	file_api_weir_v1_weir_proto_msgTypes[14].OneofWrappers = []any{
		(*BulkResponseFrame_Result)(nil),
		(*BulkResponseFrame_End)(nil),
	}
	type x struct{}
	packageMarker := x{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(packageMarker).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_weir_v1_weir_proto_rawDesc), len(file_api_weir_v1_weir_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_weir_v1_weir_proto_goTypes,
		DependencyIndexes: file_api_weir_v1_weir_proto_depIdxs,
		EnumInfos:         file_api_weir_v1_weir_proto_enumTypes,
		MessageInfos:      file_api_weir_v1_weir_proto_msgTypes,
	}.Build()
	File_api_weir_v1_weir_proto = out.File
	file_api_weir_v1_weir_proto_goTypes = nil
	file_api_weir_v1_weir_proto_depIdxs = nil
}
