"services":
  - "name": "database"
    "local":
      "max_concurrency": 4
      "max_batch_operations": 16
      "search":
        "url": "http://elasticsearch:9200"
"routes":
  - "store": "records"
    "service": "database"
